In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.2.1


In [7]:
hello = tf.constant("hello ")
world = tf.constant("世界")

In [8]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [9]:
print(result)

b'hello \xe4\xb8\x96\xe7\x95\x8c'


In [10]:
const = tf.constant(10)

In [11]:
fill_mat = tf.fill((4, 4), 10)

In [13]:
my_zeros = tf.zeros((4, 4))

In [14]:
my_ones = tf.ones((4, 4))

In [15]:
my_randn = tf.random_normal((4, 4))

In [16]:
my_randu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [17]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_randn, my_randu]

In [18]:
sess = tf.InteractiveSession()

In [19]:
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0.19447522  0.7150715   0.58322096 -0.98517984]
 [ 1.9717607  -0.9102898   0.06910058 -0.98626167]
 [-0.13500594 -0.01190828 -1.7966423   0.05714357]
 [ 0.41066048 -0.34602976  1.421544   -0.20562488]]
[[0.09948123 0.38937044 0.28876078 0.6775527 ]
 [0.41724813 0.34906018 0.5220318  0.7663226 ]
 [0.2788719  0.33470118 0.5352615  0.8530766 ]
 [0.06083763 0.72792685 0.5324782  0.86313546]]
